services:
  - type: web
    name: webbb-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist

  - type: web
    name: webbb-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        scope: secret
      - key: CLOUDINARY_API_KEY
        scope: secret
      - key: CLOUDINARY_API_SECRET
        scope: secret
      - key: CLOUDINARY_CLOUD_NAME
        scope: secret
